### ISSUE TITLE
Error in rule validate_nuc_nt_mapping:

### ISSUE THREAD

**Issue by kwnamhang** [twylie/viromatch#2]
Dear Todd,

First of all, I must commend you for providing such a fantastic resource prepared in Docker and snakemake!

I greatly appreciated your step-by-step installation guide. I don't have a background in bioinformatics (Molecular Biologist by training) and I was very happy that I could get the pipeline installed and running locally without major issues.

However, when performing a test run I came across the following error (below). I noticed that in the downloaded ViroMatch database, a .fastq file was absent within /viral-only/nuc folder. Instead, I used **ncbi_viral_refseq_gn_20191120.fna**. Could this have caused the error? 

![image](https://user-images.githubusercontent.com/22379655/119949587-5cc4a180-bfdd-11eb-84a5-5d1f63eca684.png)

Full log of the script I ran attached as .docx file.

Many thanks in advance!

Best regards,
Ki Wook (UNSW, Sydney, Australia)

[error_log.docx](https://github.com/twylie/viromatch/files/6559209/error_log.docx)

**Comment by kwnamhang** [comment]
GNU nano 2.0.6      File: INPUT.r2.validate.nuc.56.sam.log                    

[E::bwa_idx_load_from_disk] fail to locate the index files

**Comment by twylie** [comment]
Thanks for taking an interest in ViroMatch and reaching out. I've not had time to delve too deeply into your log files, but I do immediately see a few fundamental issues. Let's tackle them first and see if that resolves your problems...

First, ViroMatch only works with the database files provided here:

https://app.globus.org/file-manager?origin_id=b578a7a6-2cf1-11eb-b16b-0ee0d5d9299f&origin_path=%2F

That is, you can't just download a viral database and plug it in; that won't work. This is for a few reasons but mainly because the databases have been formatted in a manner that allows ViroMatch to quickly look up the taxonomy for a reference sequence entry (the sequence headers have been encoded with taxon ids). I'm not sure why you couldn't see all of the database files through Globus, but I encourage you to try and download all of the database files again using the following Globus link listed above.

Second, it is important to download ALL of the database files and keep them organized together. For example, when downloading the viral-only nucleotide database, the directory structure looks like this:

```
viral-only/nuc/DATE
viral-only/nuc/index_version.txt
viral-only/nuc/myCmd.sh
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.amb
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.ann
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.bwt
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.MD5
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.pac
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.sa
```

Download everything, but the main files of interest are:

```
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.amb
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.ann
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.bwt
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.pac
viral-only/nuc/ncbi_viral_refseq_gn_20191120.fna.sa
```

While the FASTA .fna file is human readable, the other files (.amb, .ann, .bwt, .pac, .sa) are also required as they are indexed versions of the FASTA file that are used in the pipeline to make alignments, etc.

The same applies to the other databases you will download using Globus---all files should be downloaded.

When you receive an error like:
`
E::bwa_idx_load_from_disk] fail to locate the index files`

...it means that either (1) the underlying index files are missing or (2) the path to the index files is not correctly passed on the ViroMatch command line or (3) if running a Docker container, the Docker-volume-mapping path does not match what is called on the command line when running ViroMatch.

Your log file indicates that ViroMatch has run up to the `validate_nuc_nt_mapping step`, which is the first time that the split NT nucleotide files have been used. Make sure that all of the split database files have been downloaded. For example, one of the split NT validation databases will have the following files associated (including the required indexes):

```
ncbi/nt/nt-1.fna
ncbi/nt/nt-1.fna.amb
ncbi/nt/nt-1.fna.ann
ncbi/nt/nt-1.fna.bwt
ncbi/nt/nt-1.fna.pac
ncbi/nt/nt-1.fna.as
```

You will need all of the split files (nt1-nt75) and their index files.

I see in your command:

```
viromatch \
--sampleid 'Test_4' \
--input /data/1_S1_L001_R1.fastq /data/1_S1_L001_R2.fastq \
--outdir /outdir/myTest_4 \
--nt /nt/nt.fofn \
--nr /nr/nr.fofn \
--viralfna /viralnuc/ncbi_viral_refseq_gn_20191120.fna \
--viralfaa /viralaa/ncbi_viral_refseq_gn_20191120.dmnd \
--host /host/GRCh38_latest_genomic.fna \
--adaptor /adaptor/adaptor.fqtrim \
--taxid /taxonomy/taxonomy.tsv \
--keep
```

...that you used the /nt/nt.fofn option to associate the split database paths. What does this file look like? Does it point to the downloaded databases as Docker sees it? A simple test is to load your Docker container with the volume mappings as you intend to run ViroMatch and then simply list the first path in the nt.fofn file. Can you see this file?

SHORT SUMMARY:

1. ViroMatch requires all of the database files provided through Globus to run correctly, including associated index files.
2. Your log indicates ViroMatch can't see the NT validation split databases: (1) the underlying index files are missing or (2) the path to the index files is not correctly passed on the ViroMatch command line or (3) if running a Docker container, the Docker-volume-mapping path does not match what is called on the command line when running ViroMatch.
3. A simple test is to make sure that your Docker container instance can list/see the file paths listed in the nt.fofn you have supplied.

Please let me know this helps resolve the problem.

PS: Can you provide your nt.fofn file and also your command to launch the Docker container for reference? Thanks.

Best,
Todd

**Comment by kwnamhang** [comment]
Thank you Todd for the detailed response and many thanks in advance for the following, as errors persist...

Responses to your summary points:

1. Database files from Globus: I confirmed that indeed, all database files including associated index files were correctly downloaded.

2. The main issue I think was the **nt.fofn file** as you mentioned. When I opened them, they originally had file paths "/db/databases/ncbi/nt/nt-10.fna" etc. I have now changed them to be "/nt/nt-10.fna". This seems to have resolved some of the issue, as the script continues to run beyond the first attempt of **validate_nuc_nt_mapping step**

3. I believe the Docker container instance can now see the file paths listed with the modified nt.fofn (attached as pdf)

**The command I used to launch the Docker container:**

![image](https://user-images.githubusercontent.com/22379655/120973456-4de6a780-c7b2-11eb-8fa0-6e17f2563373.png)

**The most recent command I used to run ViroMatch from a single .bam file:**

![image](https://user-images.githubusercontent.com/22379655/120973880-d8c7a200-c7b2-11eb-8aab-a1d7ab0b10c6.png)

**The latest error log after running with modified nt.fofn:**

![image](https://user-images.githubusercontent.com/22379655/120973810-c2214b00-c7b2-11eb-99e4-861ff5f42166.png)

P.S. Perhaps a silly question. I am trying to run this on a quad-core macbookpro with 16gb RAM. However, it lacks local disk space, so I've opted to read the database files off an external HDD (hence, the volume-mapping paths: -v /Volumes/KW_Kaysie(name of my HDD)/...). Could this be one of the reasons for the above failed run?

[nt.fofn.pdf](https://github.com/twylie/viromatch/files/6606527/nt.fofn.pdf)
